<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AddBrand.aspx.cs" Inherits="Shopp_NewThings.WebForm6" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="form-horizontal">
            <h2>Add Brand</h2>
            <hr />
            <div class="form-group">
                <asp:Label ID="Label3" runat="server" CssClass="col-md-2 control-label" Text="MainCategory Name"></asp:Label>
                <div class="col-md-3">
                    <asp:DropDownList ID="ddlMainCategory" CssClass="form-control" runat="server" OnSelectedIndexChanged="ddlMainCategory_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                    <%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="ddlCategory" InitialValue="0"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <asp:Label ID="Label2" runat="server" CssClass="col-md-2 control-label" Text="Category Name"></asp:Label>
                <div class="col-md-3">
                    <asp:DropDownList ID="ddlCategory" CssClass="form-control" runat="server"></asp:DropDownList>
                    <%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="ddlCategory" InitialValue="0"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <asp:Label ID="Label1" runat="server" CssClass="col-md-2 control-label" Text="Brand Name"></asp:Label>
                <div class="col-md-3">
                    <asp:TextBox ID="txtBrandName" CssClass="form-control" runat="server"></asp:TextBox>
<%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidatorUsername" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="txtBrandName"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2"></div>
                <div class="col-md-6">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="btnAdd_Click" />
                </div>
            </div>
        </div>

        <h1>Brands</h1>
        <hr />
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">All Brands</div>
            <asp:GridView ID="grdVeiwBrands" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" runat="server" class="table"
                OnRowEditing="grdVeiwBrands_RowEditing" OnRowCancelingEdit="grdVeiwBrands_RowCancelingEdit" OnRowUpdating="grdVeiwBrands_RowUpdating" OnRowDeleting="grdVeiwBrands_RowDeleting">
                <Columns >
                    <asp:TemplateField HeaderText="BrandID">
                        <ItemTemplate>
                           <asp:Label ID="lblBrandID" runat="server" Text='<%# Eval("BrandID") %>'></asp:Label>
                        </ItemTemplate>
                        <%--<EditItemTemplate>
                            <asp:TextBox ID="txtEditBrandID" runat="server" Text='<%# Eval("BrandID") %>'></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="BrandName">
                        <ItemTemplate>
                           <asp:Label ID="lblBrandName" runat="server" Text='<%# Eval("BrandName") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEditBrandName" runat="server" Text='<%# Eval("BrandName") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="MainCatId">
                        <ItemTemplate>
                           <asp:Label ID="lblMainCatId" runat="server" Text='<%# Eval("MainCatId") %>'></asp:Label>
                        </ItemTemplate>
                       <%-- <EditItemTemplate>
                            <asp:TextBox ID="txtEditMainCatIde" runat="server" Text='<%# Eval("MainCatId") %>'></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
