<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AddMainCategory.aspx.cs" Inherits="Shopp_NewThings.WebForm8" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
            <div class="container">
        <div class="form-horizontal">
            <h2>Add MainCategory</h2>
            <hr />
            <div class="form-group">
                <asp:Label ID="Label1" runat="server" CssClass="col-md-2 control-label" Text="MainCategory Name"></asp:Label>
                <div class="col-md-3">
                    <asp:TextBox ID="txtMainCatName" CssClass="form-control" runat="server"></asp:TextBox>
<%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidatorUsername" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="txtCatName"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2"></div>
                <div class="col-md-6">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="btnAdd_Click" />
                </div>
            </div>
        </div>
        <h1>Categories</h1>
        <hr />
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">All Categories</div>
            <asp:GridView ID="grdVeiwMainCategories" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" runat="server" class="table"
                OnRowEditing="grdVeiwMainCategories_RowEditing" OnRowCancelingEdit="grdVeiwMainCategories_RowCancelingEdit" OnRowUpdating="grdVeiwMainCategories_RowUpdating" OnRowDeleting="grdVeiwMainCategories_RowDeleting">
                <Columns>
                    <asp:TemplateField HeaderText="MainCategoryID">
                        <ItemTemplate>
                            <asp:Label ID="lblMainCatID" runat="server" Text='<%# Eval("MainCatID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="MainCategoryName">
                        <ItemTemplate>
                            <asp:Label ID="lblMainCatName" runat="server" Text='<%# Eval("MainCatName") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEditMainCatName" runat="server" Text='<%# Eval("MainCatName") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
