<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AddSubCategory.aspx.cs" Inherits="Shopp_NewThings.WebForm16" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="container">
        <div class="form-horizontal">
            <h2>Add Sub Category</h2>
            <hr />
            <div class="form-group">
                <asp:Label ID="Label1" runat="server" CssClass="col-md-2 control-label" Text="Main Category"></asp:Label>
                <div class="col-md-3">
                    <asp:DropDownList ID="ddlMainCategory" CssClass="form-control" AutoPostBack="true" runat="server" OnSelectedIndexChanged="ddlMainCategory_SelectedIndexChanged"></asp:DropDownList>
<%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="ddlCategory" InitialValue="0"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <asp:Label ID="Label11" runat="server" CssClass="col-md-2 control-label" Text="Category"></asp:Label>
                <div class="col-md-3">
                    <asp:DropDownList ID="ddlCategory" CssClass="form-control" runat="server"></asp:DropDownList>
<%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="ddlCategory" InitialValue="0"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
             <div class="form-group">
                <asp:Label ID="Label2" runat="server" CssClass="col-md-2 control-label" Text="Sub Category"></asp:Label>
                <div class="col-md-3">
                   <asp:TextBox ID="txtSubCatName" CssClass="form-control" runat="server"></asp:TextBox>
<%--                    <asp:RequiredFieldValidator ID="RequiredFieldValidatorUsername" CssClass="text-danger" runat="server" ErrorMessage="This field is Required !" ControlToValidate="txtSub2CatName"></asp:RequiredFieldValidator>--%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2"></div>
                <div class="col-md-6">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="btnAdd_Click" />
                </div>
            </div>
        </div>
          <h1>Sub2 Categories</h1>
        <hr />
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">All Sub Categories</div>
             <asp:GridView ID="grdVeiwSubCategories" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" runat="server" class="table"
                 OnRowEditing="grdVeiwSubCategories_RowEditing" OnRowCancelingEdit="grdVeiwSubCategories_RowCancelingEdit"
                 OnRowUpdating="grdVeiwSubCategories_RowUpdating" OnRowDeleting="grdVeiwSubCategories_RowDeleting">
     <Columns>
         <asp:TemplateField HeaderText="SubCategoryID">
             <ItemTemplate>
                 <asp:Label ID="lblSubCatID" runat="server" Text='<%# Eval("SubCatID") %>'></asp:Label>
             </ItemTemplate>
         </asp:TemplateField>

         <asp:TemplateField HeaderText="SubCategoryName">
             <ItemTemplate>
                 <asp:Label ID="lblSubCatName" runat="server" Text='<%# Eval("SubCatName") %>'></asp:Label>
             </ItemTemplate>
             <EditItemTemplate>
                 <asp:TextBox ID="txtEditSubCatName" runat="server" Text='<%# Eval("SubCatName") %>'></asp:TextBox>
             </EditItemTemplate>
         </asp:TemplateField> 

        <asp:TemplateField HeaderText="MainCategoryName">
            <ItemTemplate>
                <asp:Label ID="lblMainCatName" runat="server" Text='<%# Eval("MainCatName") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>

         <asp:TemplateField HeaderText="CategoryName">
             <ItemTemplate>
                 <asp:Label ID="lblCatName" runat="server" Text='<%# Eval("CatName") %>'></asp:Label>
             </ItemTemplate>
         </asp:TemplateField>
     </Columns>
 </asp:GridView>
           
            <%--<asp:Repeater ID="rptrCategory" runat="server">
                <HeaderTemplate>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Sub Category</th>
                                <th>Category</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                </HeaderTemplate>
                <ItemTemplate>
                    <tr>
                        <th><%# Eval("SubCatID") %></th>
                        <td><%# Eval("SubCatName") %></td>
                        <td><%# Eval("CatName") %></td>
                        <td>Edit</td>
                    </tr>
                </ItemTemplate>
                <FooterTemplate>
                    </tbody>
            </table>
                </FooterTemplate>
            </asp:Repeater>--%>
        </div>
    </div>
</asp:Content>
